---
- name: Change user password on BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Modify password
    bigip_user:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      username_credential:
      password_credential:
      validate_certs: False
    delegate_to: localhost
